/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/Contatos`; params?: Router.UnknownInputParams; } | { pathname: `/Exames`; params?: Router.UnknownInputParams; } | { pathname: `/Index`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Solicitar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ex-con`; params?: Router.UnknownInputParams; } | { pathname: `/../type`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ex-con copy`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/Contatos`; params?: Router.UnknownOutputParams; } | { pathname: `/Exames`; params?: Router.UnknownOutputParams; } | { pathname: `/Index`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Solicitar`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ex-con`; params?: Router.UnknownOutputParams; } | { pathname: `/../type`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ex-con copy`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Cadastro${`?${string}` | `#${string}` | ''}` | `/Contatos${`?${string}` | `#${string}` | ''}` | `/Exames${`?${string}` | `#${string}` | ''}` | `/Index${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/Solicitar${`?${string}` | `#${string}` | ''}` | `/../components/ex-con${`?${string}` | `#${string}` | ''}` | `/../type${`?${string}` | `#${string}` | ''}` | `/../components/ex-con copy${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/Contatos`; params?: Router.UnknownInputParams; } | { pathname: `/Exames`; params?: Router.UnknownInputParams; } | { pathname: `/Index`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Solicitar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ex-con`; params?: Router.UnknownInputParams; } | { pathname: `/../type`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ex-con copy`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
